runtime: python39 # or another supported version

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /stylesheets
  static_dir: www/stylesheets

- url: /js
  static_dir: www/js

- url: /images
  static_dir: www/images

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto