runtime: python39 # or another supported version

instance_class: F2

handlers:
- url: /
  static_files: src/index.html
  upload: src/index.html

- url: /stylesheets
  static_dir: src/stylesheets

- url: /js
  static_dir: src/js

- url: /images
  static_dir: src/images

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto